site_name: My Awesome Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.annotate
