name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Install dependencies
        run: |
          bundle install || bundle update

      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Check if _site exists
        run: |
          if [ -d "_site" ]; then
            echo "_site directory exists, proceeding to upload.";
          else
            echo "_site directory does not exist. Build failed!";
            exit 1;
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
