name: Convert Markdown to PDF

on:
  push:
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Convert Markdown to PDF
        run: |
          PUPPETEER_EXECUTABLE_PATH=$(which chromium-browser) \
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
          PUPPETEER_ARGS="--no-sandbox --disable-setuid-sandbox" \
          md-to-pdf README.md --config-file .md-to-pdf.json

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-pdf
          path: README.pdf
